Repository OpenTabletDriver/opentabletdriver.github.io, pull requests merged in 2023-12, with the labels that each got.

#82 README: Update site paths
  README.md
Labels: bug, documentation

#87 Refactor Platform Cards to use a for loop instead
  site/_data/operating-systems.json
  site/_includes/platformcard.html
  site/_includes/platformcards.html
Labels: enhancement

#84 dependabot: Add weekly Bundler updates
  .github/dependabot.yml
Labels: enhancement, ci

#86 Adjust title to the General FAQ in URL
  site/_wiki/FAQ/Linux.md
  site/_wiki/FAQ/Windows.md
Labels: enhancement, wiki

#89 Refactor wiki logic
  site/_config.yml
  site/_data/wiki/title-remaps.json
  site/_layouts/wiki.html
  site/_wiki/Install/Linux.md
  site/_wiki/Install/MacOS.md
  site/_wiki/Install/Windows.md
Labels: enhancement

#83 README: Adjust local development steps
  README.md
Labels: documentation, enhancement

#85 FAQ: Rename Tablet Specific FAQ to Model Specific FAQ
  site/_wiki/FAQ/General.md
  site/_wiki/FAQ/ModelSpecific.md
  site/_wiki/FAQ/TabletSpecific.md
Labels: enhancement, wiki

#62 Lint markdown in PRs
  .editorconfig
  .git-blame-ignore-revs
  .github/workflows/linter.yml
  .markdownlint.yaml
  README.md
  TODO.md
  site/_plugins/rouge-logoutput-lexer.rb
  site/_wiki/Documentation/RequiredPermissions.md
  site/_wiki/FAQ/General.md
  site/_wiki/FAQ/Linux.md
  site/_wiki/FAQ/Windows.md
  site/_wiki/FAQ/WindowsAppSpecific.md
  site/_wiki/Install/Linux.md
  site/_wiki/Install/Windows.md
  site/index.md
Labels: enhancement, ci, linting, meta

#98 FAQ/Windows: Explain `userdata` in depth
  site/_wiki/FAQ/Windows.md
Labels: enhancement, wiki

#108 wiki/ReqPermissions: Convert MacOS required permissions to table
  site/_wiki/Documentation/RequiredPermissions.md
Labels: enhancement, wiki, styling

#99 config: Use strict filters
  site/_config.yml
Labels: enhancement

#102 wiki refactor: Change links to use json file
  .editorconfig
  site/_config.yml
  site/_data/links.json
  site/_includes/header.html
  site/_wiki/Documentation/RequiredPermissions.md
  site/_wiki/FAQ/General.md
  site/_wiki/FAQ/Linux.md
  site/_wiki/FAQ/MacOS.md
  site/_wiki/FAQ/Windows.md
  site/_wiki/FAQ/WindowsAppSpecific.md
  site/_wiki/Install/Linux.md
  site/_wiki/Install/MacOS.md
  site/_wiki/Install/Windows.md
Labels: enhancement

#110 wiki cleanup: Generic rewrites or additions
  site/_wiki/Documentation/RequiredPermissions.md
  site/_wiki/FAQ/General.md
  site/_wiki/FAQ/Linux.md
  site/_wiki/FAQ/LinuxAppSpecific.md
  site/_wiki/FAQ/ModelSpecific.md
  site/_wiki/FAQ/Windows.md
  site/_wiki/FAQ/WindowsAppSpecific.md
  site/_wiki/Install/Linux.md
  site/_wiki/Install/MacOS.md
  site/_wiki/Install/Windows.md
Labels: enhancement, wiki

#101 wiki/Logs: Split exception log location into its own section
  .github/workflows/linter.yml
  README.md
  site/_includes/appdata-location.md
  site/_wiki/Documentation/Logs.md
  site/_wiki/FAQ/General.md
Labels: enhancement, wiki

#100 Wiki/Configs: Add 'Attributes' section
  site/_wiki/Development/Configurations.md
Labels: enhancement, wiki

#122 favicon.ico: Use ico file from main project
  site/favicon.ico
Labels: bug

#123 workflows: Restrict actions push conditions to just 'main'
  .github/workflows/jekyll.yml
  .github/workflows/linter.yml
Labels: enhancement, ci

#124 inject-anchors: Refactor and enable blink on 'hashchange'
  site/assets/js/inject-anchors.js
Labels: enhancement

#125 Cache busting CSS/JS using a query string
  site/_includes/scripts.html
  site/_includes/styles.html
  site/_plugins/get-asset.rb
Labels: bug

#129 js/inject-anchors: Use optional chaining
  site/assets/js/inject-anchors.js
Labels: bug

#138 Add openSUSE installation steps
  site/_data/links.json
  site/_wiki/Install/Linux.md
Labels: enhancement, wiki
