Repository OpenTabletDriver/opentabletdriver.github.io, pull requests merged in 2023-11, with the labels that each got.

#23 Use direct links for latest version downloads
  Release/Download/OpenTabletDriver.deb.md
  Release/Download/OpenTabletDriver.linux-x64.tar.gz.md
  Release/Download/OpenTabletDriver.osx-x64.tar.gz.md
  Release/Download/OpenTabletDriver.rpm.md
  Release/Download/OpenTabletDriver.win-x64.zip.md
  _config.yml
  _wiki/Install/Linux.md
  _wiki/Install/MacOS.md
  _wiki/Install/Windows.md
Labels: enhancement

#24 Clean up config file and use values as intended
  _config.yml
  index.md
Labels: documentation, enhancement

#25 Remove redirects
  _config.yml
  _includes/header.html
  _layouts/redirect.html
  _sections/Changelog.md
  _sections/Discord.md
  _sections/GitHub.md
  _wiki/FAQ/Linux.md
  _wiki/FAQ/Windows.md
Labels: enhancement

#35 config: Fix typo in site description
  _config.yml
Labels: enhancement

#60 Add Jekyll CI
  .github/workflows/jekyll.yml
Labels: enhancement, ci, meta

#69 Simplify body and header whitespace
  _includes/header.html
  _layouts/default.html
  assets/css/site.scss
Labels: enhancement, styling

#74 Test site paths
  .github/workflows/jekyll.yml
  _config.yml
  run-tests.sh
  tests/check-site-paths/check-site-paths.sh
Labels: enhancement, ci, linting, meta

#68 sections: Permalink to path
  _config.yml
Labels: enhancement

#76 workflows: Add HTML Verification
  .github/workflows/jekyll-build-workflow.yml
  .github/workflows/jekyll.yml
  .github/workflows/site-workflow/action.yml
  .gitignore
  README.md
  Rakefile
  _config.yml
  _includes/header.html
  _includes/platformcard.html
  _layouts/plugins.html
  _wiki/Documentation/WindowsInk.md
  _wiki/FAQ/General.md
  _wiki/FAQ/TabletSpecific.md
Labels: enhancement, ci, linting, meta
